# See https://circleci.com/docs/2.0/language-ruby/ for a guide on building a Circle CI config file
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - timevalue-{{ checksum "Gemfile.lock" }}
            - timevalue-

      - run:
          name: Bundle Install
          command: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: timevalue-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run: bundle exec rspec --format progress
